### PR TITLE
WASM SIMD for NNUE 

### PR DESCRIPTION
**Pull request by hi-ogawa**
EDIT: I removed `NOTE.md` from the repository and move its content to here https://github.com/hi-ogawa/stockfish.wasm/wiki/NOTE

Hi @niklasf
I experimented with WASM SIMD and wanted to share the result, which looks promising even though I'm not sure if it's usable stage.

I've seen the closed PR (https://github.com/niklasf/stockfish.wasm/pull/21) where it relied on emscripten's x86 SIMD emulation feature, but here, I implemented some linear algebra routines directly using WASM SIMD intrisics.

These are some benchmark results (see NOTE.md for the detail)

```
# NOTE:
#  emscripten's node (emsdk/node/12.18.1_64bit/bin/node) is old and doesn't seem to compatible with latest simd (cf. https://github.com/emscripten-core/emscripten/issues/11484).
#  So, I'm using the locally installed node with this version.
$ node -e 'console.log(`node: ${process.version}\nv8: ${process.versions.v8}`)'
node: v15.8.0
v8: 8.6.395.17-node.23

# [ Build type `wasm_simd_post_mvp=yes` ]
$ node --experimental-wasm-{simd,threads} --experimental-repl-await --wasm-simd-post-mvp

> const sf = await require("./stockfish")();

> sf.postMessage("bench 16 1 22 current depth classical");
Total time (ms) : 5056
Nodes searched  : 3478378
Nodes/second    : 687970

> sf.postMessage("bench 16 1 22 current depth NNUE");
Total time (ms) : 6424
Nodes searched  : 2670151
Nodes/second    : 415652


# [ Build type `wasm_simd=yes wasm_simd_post_mvp=no` ]
> sf.postMessage("bench 16 1 22 current depth NNUE");
Total time (ms) : 9472
Nodes searched  : 2670151
Nodes/second    : 281899


# [ Build type `wasm_simd=no wasm_simd_post_mvp=no` ]
> sf.postMessage("bench 16 1 22 current depth NNUE");
Total time (ms) : 54008
Nodes searched  : 2670151
Nodes/second    : 49439
```

As a comparison, these are the results from current stockfish master (29ed22d) on my machine.

```
# Built with flag `ARCH=x86-64-modern` which enables SSSE3.
bench 16 1 22 current depth classical
Total time (ms) : 4323
Nodes searched  : 4850165
Nodes/second    : 1121944

bench 16 1 22 current depth NNUE
Total time (ms) : 2992
Nodes searched  : 2655513
Nodes/second    : 887537

# Built with `ARCH=x86-64 sse=yes sse2=yes SUPPORTED_ARCH=true` (SSE3 is disabled)
# I think this setting is the closest one we can get to with WASM SIMD.
bench 16 1 22 current depth NNUE
Total time (ms) : 5202
Nodes searched  : 2655513
Nodes/second    : 510479
```

A few things I wanted to mention:

- I made a separate file `nnue/math.cpp` and WASM SIMD matrix-vector multiplication routine lives there (mostly because I wanted separate translation unit so that I can rebuild faster).

- I added two build types `wasm_simd` and `wasm_simd_post_mvp`, where `wasm_simd_post_mvp` has substantially faster implementation due to new intrinsic `__builtin_wasm_dot_s_i32x4_i16x8`.

- NNUE data is embedded in executable by generating c++ string literal with my little script `embedded_nnue_data.py`,
  which means the size of `stockfish.wasm` becomes 21MB.

- I made `bench_eval` command to measure directly the performance of NNUE inference with my another little script `timeit.hpp`.

- It seems both Chrome/Chromium(88.0.4324.150) and Firefox(85.0.1) already enables "post-mvp" features when SIMD is enabled.

- On Firefox, there is some security restriction regarding `SharedArrayBuffer` and it needs some special http headers to be sent.
  So, I included `misc/server.py` to run http server with such headers.

At this point, I'm not really sure if this should be even PR, but I'm curious what you think about this.
For the next step, I'm planning to implement a way to run javscript as UCI engine executable so that we can compare two versions' strengths direcly by pitting (e.g. by cutechess-cli).

Thanks a lot for reading!

### CODE REVIEW

**Comment by niklasf** [comment]
Wow, amazing work!

Do you know if browsers have a good way to test for the required post MVP features? If so, it should be possible to get a test version out on Lichess pretty quickly.

**Comment by hi-ogawa** [comment]
Thanks for the reply!

> Do you know if browsers have a good way to test for the required post MVP features?

Probably, we have to check the wasm binary itself by [WebAssembly.validate](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/validate).
But, of course, we don't want to download a whole wasm file before knowing if it runs, so one idea is that, maybe before downloading, we can just validate some small wasm binary with simd opcode we want to use.
I think I can make some example right away, let's see.

**Comment by hi-ogawa** [comment]
I think I found a very quick way to check if certain wasm opcode is supported. It's something like this:

```
# Feature detection for `i32x4.dot_i16x8_s` (see `misc/feature_detection.wat` for how these bytes are generated)

/usr/bin/node --experimental-wasm-simd
> data = Uint8Array.from([0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 123, 3, 2, 1, 0, 7, 8, 1, 4, 116, 101, 115, 116, 0, 0, 10, 15, 1, 13, 0, 65, 0, 253, 17, 65, 0, 253, 17, 253, 186, 1, 11])
> WebAssembly.validate(data)
false

/usr/bin/node --experimental-wasm-simd --wasm-simd-post-mvp
> data = Uint8Array.from([0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 123, 3, 2, 1, 0, 7, 8, 1, 4, 116, 101, 115, 116, 0, 0, 10, 15, 1, 13, 0, 65, 0, 253, 17, 65, 0, 253, 17, 253, 186, 1, 11])
> WebAssembly.validate(data)
true
```

**Comment by hi-ogawa** [comment]
I implemented `uci.js` to run this stockfish as an UCI engine executable.
Also, I added new github actions `match.yml` which runs cutechess-cli tornament between two versions (nnue and classical).
It's only triggered manually (`workflow_dispatch` mode) and I just started four tournaments on my repository.
You can check progress and result here https://github.com/hi-ogawa/stockfish.wasm/actions?query=workflow%3AMatch.
(Probably, Github CI is not really a good place to run engine testing, but I've been using this approach for my own engine because I don't have a machine to spare.)

Four tournaments settings are

- nnue(wasm_simd_post_mvp=yes) vs classical, tc=10+0.1
- nnue(wasm_simd_post_mvp=yes) vs classical, tc=60+0.6
- nnue(wasm_simd=yes) vs classical, tc=10+0.1
- nnue(wasm_simd=yes) vs classical, tc=60+0.6

each with 100 rounds.

**Comment by hi-ogawa** [comment]
I was crawling through v8's code and I found that actually `__builtin_wasm_dot_s_i32x4_i16x8` is not "post mvp" anymore since v8 version 8.8.101 https://github.com/v8/v8/commit/01b8b3e09b5d0bd66b820887ad1bb5a68d48692b.
On my machine, NodeJS has v8 (8.6.395.17) and Chromium has v8 (8.8.278.15), so that's the reason why the fast version is able to run on Chromium.
Essentially what I thought "post mvp" build might not be "post mvp" build anymore, but this fact itself indicates such feature is not really stable yet.

**Comment by hi-ogawa** [comment]
I made a little frontend `misc/uci.html` where you can run uci command for quick testing. I published it as my fork's Github Page here https://hi-ogawa.github.io/stockfish.wasm/misc/uci.html.

**Comment by niklasf** [comment]
Still very impressed with your work. I also see you have created a much cleaner port of Stockfish at https://github.com/hi-ogawa/Stockfish/tree/emscripten. To me it would make sense to stop maintaining this repository in favor of yours. Are you planning to publish it to npm?

**Comment by hi-ogawa** [comment]
Thanks for noticing my port!
I was just experimenting with emscripten's `ASINCIFY` and `PROXY_TO_PTHREAD`, and (somehow) managed it to work. There's a bit sketchy part in the uci command communication but I think (hope) it doesn't have a problem.

> Are you planning to publish it to npm?

I wasn't planning to make npm package, but sure, I can do that.
So, after publishing npm package from my repo, I will update lila's PR https://github.com/ornicar/lila/pull/8154 too accordingly.

**Pull request closed without merging**
