### PR TITLE
Make nnue build by merging from master

### PR DESCRIPTION
**Pull request by Artoria2e5**
Okay, I thought it's about the flags, but it's really about the mymindstorm thing. I don't really see any real point for the PR, since you guys can just merge from upstream instead of doing the cherry-picked nnue branch.

### CODE REVIEW

**Comment by Artoria2e5** [comment]
Wait, it actually requires `-m`? I have this urge to just switch to simd-everywhere, but allow me to try and reproduce how it last failed...

**Comment by Artoria2e5** [comment]
……woah. this is… unexpected.

**Comment by niklasf** [comment]
You mean I should simply merge from upstream master? My last attempt was #21. Has anything changed since then?

**Comment by niklasf** [comment]
To clarify, the issue was never an outright build failure, just catastrophic performance regression.

**Comment by niklasf** [comment]
#21 is still slow after the recent changes.

**Pull request closed without merging**
